"use server";
import endpoints from "@/constants/endpoints";
import { ActionResponse } from "@/types/api";
import secureFetch from "@/utils/fetch";
import { getRandomInt } from "@/utils/number";
import { attachements } from "./mock/attachements";
export type GetRestaurantResponse = {
  id: string;
  name: string;
  slug: string;
  phone: string;
  alt_phone: string;
  email: string;
  website: string;
  description: string;
  address: string;
  governorate: string;
  delegation: string;
  town: string;
  postal_code: string;
  lat: number;
  lng: number;
  cover: string;
  logo: string;
  verified: boolean;
  public: boolean;
  published_by: number;
  accepted_by: number | null;
  created_at: string;
  updated_at: string;
  images: string[];
};
export const getRestaurantById = async (id: string) => {
  const data = await secureFetch(`${endpoints.RESTAURANTS}/${id}`);
  return data as ActionResponse<GetRestaurantResponse>;
};
